name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest
    container: rust:latest

    steps:
    - uses: actions/checkout@v2
    - name: Update cache
      run: DEBIAN_FRONTEND="noninteractive" apt-get update
    - name: Install apt packages
      run: DEBIAN_FRONTEND="noninteractive" apt-get install -y libudev-dev
    - name: Build project
      run: cargo build --all --verbose
